/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nathaniel_amendroid7z_Main */

#ifndef _Included_com_nathaniel_amendroid7z_Main
#define _Included_com_nathaniel_amendroid7z_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nathaniel_amendroid7z_Main
 * Method:    doeverything
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nathaniel_amendroid7z_Main_doeverything
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
